---
- name: Download Benchmark
  git:
    repo: 'https://github.com/docker/docker-bench-security.git'
    version: HEAD
    dest: /benchmark/
    update: no
  tags:
    - skip_ansible_lint

- name: Copy test runner script to host
  copy:
    src: run_check.sh
    dest: /benchmark/
    owner: root
    group: root
    mode: 0700

- import_tasks: "{{ role_path }}/tasks/section-1.yml"
#  when: level_1_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-2.yml"
#  when: level_1_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-3.yml"
  when: level_3_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-4.yml"
  when: level_4_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-5.yml"
  when: level_5_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-6.yml"
  when: level_6_checks is defined

- import_tasks: "{{ role_path }}/tasks/section-7.yml"
  when: level_7_checks is defined

- name: Remove security benchmark
  file:
    state: absent
    path: "/benchmark"
