---
# TBD ADD A CHECK IF SWARM IS ENABLED, THEN DO TESTS...
- name: 7 - Docker Swarm Configuration
  shell: ./run_check.sh "{{ item }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - check_7_1
    - check_7_2
    - check_7_3
    - check_7_4
    - check_7_5
    - check_7_6
    - check_7_7
    - check_7_8
    - check_7_9
    - check_7_10
