---
- name: 1 Host Configuration
  shell: ./run_check.sh "{{ item }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - check_1_1
    - check_1_2
    - check_1_3
    - check_1_4
    - check_1_5
    - check_1_6
    - check_1_7
    - check_1_8
    - check_1_9
    - check_1_10
    - check_1_11
    - check_1_12
    - check_1_13
