---
- name: 1 Host Configuration
  shell: ./run_check.sh "{{ item.check }}" "{{ item.scored }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - { check: check_1_1, scored: 1 }
    - { check: check_1_2, scored: 0 }
    - { check: check_1_3, scored: 0 }
    - { check: check_1_4, scored: 1 }
    - { check: check_1_5, scored: 1 }
    - { check: check_1_6, scored: 1 }
    - { check: check_1_7, scored: 1 }
    - { check: check_1_8, scored: 1 }
    - { check: check_1_9, scored: 1 }
    - { check: check_1_10, scored: 1 }
    - { check: check_1_11, scored: 1 }
    - { check: check_1_12, scored: 1 }
    - { check: check_1_13, scored: 1 }
