---
- name: 3 - Docker daemon configuration files
  shell: ./run_check.sh "{{ item }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - check_3_1
    - check_3_2
    - check_3_3
    - check_3_4
    - check_3_5
    - check_3_6
    - check_3_7
    - check_3_8
    - check_3_9
    - check_3_10
    - check_3_11
    - check_3_12
    - check_3_13
    - check_3_14
    - check_3_15
    - check_3_16
    - check_3_17
    - check_3_18
