---
- name: 2 - Docker daemon configuration
  shell: ./run_check.sh "{{ item }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - check_2_1
    - check_2_2
    - check_2_3
    - check_2_4
    - check_2_5
    - check_2_6
    - check_2_7
    - check_2_8
    - check_2_9
    - check_2_10
    - check_2_11
    - check_2_12
    - check_2_13
    - check_2_14
    - check_2_15
    - check_2_16
    - check_2_17
    - check_2_18
