---
- name: 2 - Docker daemon configuration
  shell: ./run_check.sh "{{ item.check }}" "{{ item.scored }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - { check: check_2_1, scored: 1 }
    - { check: check_2_2, scored: 1 }
    - { check: check_2_3, scored: 1 }
    - { check: check_2_4, scored: 1 }
    - { check: check_2_5, scored: 1 }
    - { check: check_2_6, scored: 1 }
    - { check: check_2_7, scored: 1 }
    - { check: check_2_8, scored: 1 }
    - { check: check_2_9, scored: 1 }
    - { check: check_2_10, scored: 1 }
    - { check: check_2_11, scored: 1 }
    - { check: check_2_12, scored: 1 }
    - { check: check_2_13, scored: 1 }
    - { check: check_2_14, scored: 1 }
    - { check: check_2_15, scored: 1 }
    - { check: check_2_16, scored: 1 }
    - { check: check_2_17, scored: 1 }
    - { check: check_2_18, scored: 1 }
