---
- name: 4 - Container Images and Build File
  shell: ./run_check.sh "{{ item }}"
  args:
    chdir: /benchmark/
    executable: /bin/bash
  register: check_pass
  failed_when: check_pass.rc != 0
  with_items:
    - check_4_1
    - check_4_2
    - check_4_3
    - check_4_4
    - check_4_5
    - check_4_6
    - check_4_7
    - check_4_8
    - check_4_9
    - check_4_10
    - check_4_11
