---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  - name: Ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create:  docker/create.yml
    prepare: docker/prepare.yml
    destroy: docker/destroy.yml
scenario:
  name: default
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
  enabled: false
